# config.yaml

# Data paths
data:
  s2_dir: "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/final/s2_patches_multi"
  lidar_dir: "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/final/lidar_patches"

# Training parameters
training:
  batch_size: 8
  epochs: 200
  lr: 0.0001
  timesteps: 1000
  noise_schedule: "linear"
  num_workers: 16
  context_k: 1
  randomize_context: false
  loss:
    name: "masked_mse_loss"  
    alpha: 0.1 

# Model parameters
model:
  unet_depth: 4
  base_channels: 128
  embed_dim: 256
  attention_variant: "default"
  

# Logging and saving
logging:
  wandb_project: "final_dissertation"
  wandb_name: null
  run_name: "default_run"
  save_dir: "./models"
  output_dir: "./reconstructions"

# Sampling and evaluation
evaluation:
  sampling_methods:
    - ddpm
  evaluate: false
  eval_index_json: "fixed_eval.json"

# System settings
system:
  device: "auto"
  debug: false