# config.yaml

# Data paths
data:
  s2_dir: "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/master_model/s2_patches_multi"
  lidar_dir: "/cs/student/projects2/aisd/2024/tcannon/dissertation/Dissertation/master_model/lidar_patches"

# Training parameters
training:
  batch_size: 8
  epochs: 200
  lr: 0.0001
  timesteps: 1000
  noise_schedule: "linear"
  num_workers: 4
  context_k: 1
  randomize_context: false

# Model parameters
model:
  unet_depth: 4
  base_channels: 128
  embed_dim: 256
  attention_variant: "default"

# Logging and saving
logging:
  wandb_project: "final_dissertation"
  wandb_name: null
  run_name: "default_run"
  save_dir: "./models"
  output_dir: "./reconstructions"

# Sampling and evaluation
evaluation:
  sampling_methods:
    - ddpm
  evaluate: false
  eval_index_json: "fixed_eval.json"

# Diffusion parameters
diffusion:
  sigma_data: 0.5
  sigma_min: 0.002
  sigma_max: 80.0

# System settings
system:
  device: "auto"
  debug: false